`ifndef QOSOC_DEBUG_STATUS_DEFS_VH
`define QOSOC_DEBUG_STATUS_DEFS_VH

`define QOSOC_DBG_ERR_NONE  8'h00
`define QOSOC_DBG_ERR_BUS   8'h01
`define QOSOC_DBG_ERR_BUSY  8'h02
`define QOSOC_DBG_ERR_ARG   8'h03
`define QOSOC_DBG_ERR_EMPTY 8'h04

`define QOSOC_DBG_EVT_DEBUG_ENTRY 8'h01
`define QOSOC_DBG_EVT_BUS_ERROR   8'h02
`define QOSOC_DBG_EVT_MBIST_START 8'h03
`define QOSOC_DBG_EVT_MBIST_DONE  8'h04
`define QOSOC_DBG_EVT_MBIST_FAIL  8'h05
`define QOSOC_DBG_EVT_WAKE        8'h06
`define QOSOC_DBG_EVT_PWR_STATE   8'h07
`define QOSOC_DBG_EVT_PWR_EN      8'h08
`define QOSOC_DBG_EVT_TRAP        8'h09
`define QOSOC_DBG_EVT_SCRATCH     8'h0A

`endif
